// app/layout.tsx (still server component)
import "./globals.css";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/theme/theme-provider";
import LayoutShell from "@/components/utils/LayoutShell";
import AuthProvider from "./providers/AuthProvider";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dryink",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem={false}
          disableTransitionOnChange
        >
          <Toaster />
          <AuthProvider>
          <LayoutShell>
              {children}
              </LayoutShell>
            </AuthProvider>
        </ThemeProvider>
        
      </body>
    </html>
  );
}
